### PR TITLE
Move test-frame to 0.8.0 + use sequential deletion

### PR DESCRIPTION
**Pull request by kornys**
Could you please test it if it work properly?

### CODE REVIEW

**Comment by jiridanek** [comment]
Checking, upgrade test will run 30 mins, then we'll see if it helps. Thanks

**Comment by jiridanek** [comment]
I think I see

https://github.com/skodjob/odh-e2e/blob/42a1f334c37885a4a42ed22521958b5c91c58803/src/test/java/io/odh/test/e2e/upgrade/UpgradeAbstract.java#L44

This one needs to be configured too, maybe?

**Comment by kornys** [comment]
@jiridanek yes it has to be, I thought that it inherid values but it overrides it, so it has to be added to others, let me do a fix

**Review by jiridanek — APPROVED** [review]
Tried this out. Out of 6 CI runs, three got stuck and died on jenkins timeout, two passed, and one timeouted with

```
2024-10-22T13:44:07 ERROR [Wait:106] Exception waiting for: DataScienceCluster upgrade-dsc readiness, Failure executing: GET at: https://api.crc.testing:6443/apis/datasciencecluster.opendatahub.io/v1/datascienceclusters/upgrade-dsc. Message: Unauthorized. Received status: Status(apiVersion=v1, code=401, details=null, kind=Status, message=Unauthorized, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Unauthorized, status=Failure, additionalProperties={}).
2024-10-22T13:44:07 ERROR [Wait:116] Timeout after 600000 ms waiting for DataScienceCluster upgrade-dsc readiness
io.skodjob.testframe.wait.WaitException: Timeout after 600000 ms waiting for DataScienceCluster upgrade-dsc readiness
```

I think this is good to go, I'll investigate more on how to improve the job success rate.

**Pull request merged**
